apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  - path: config/upstream
    contents:
      - path: .
        githubRelease:
          slug: knative/eventing
          tag: knative-v1.5.1
          disableAutoChecksumValidation: true
        includePaths:
          - eventing-crds.yaml
          - eventing.yaml
